"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { setSessionAccessToken } from "@/lib/auth/session";

function Mark() { return <div className="auth-mark" aria-label="Ethiopia Customs Commission"><span>◉</span><b>✦</b><strong>♢</strong><small>ETHIOPIA CUSTOMS COMMISSION</small></div>; }

export function AuthShell({ children, signup = false }: { children: React.ReactNode; signup?: boolean }) {
  return <div className="auth-page"><section className="auth-hero"><div className="auth-hero-brand">ETHIOPIA<br/>CUSTOMS COMMISSION</div><div className="auth-hero-copy"><p>SECURE BORDERS</p><p>PROSPEROUS NATION</p><span>Facilitating Trade<br/>for a Brighter Tomorrow</span></div><div className="auth-pillars"><span>◯ <b>SECURE<br/>OPERATIONS</b></span><span>▥ <b>EFFICIENT<br/>TRADE</b></span><span>♧ <b>STRONGER<br/>ECONOMY</b></span></div><div className="auth-hero-footer">ETHIOPIA CUSTOMS COMMISSION</div></section><section className="auth-card">{signup && <Link href="/login" className="back-link">← &nbsp;Back to Login</Link>}<div className="language">◎ &nbsp; English⌄</div>{!signup && <Mark/>}{children}<footer>© 2026 Customs Commission. All rights reserved.<span>Privacy &nbsp; | &nbsp; Help &nbsp; | &nbsp; Contact</span></footer></section></div>;
}

export function LoginForm() {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const router = useRouter();
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); if (!data.get("identity") || !data.get("password")) { setError("Enter your username/email and password."); return; } setBusy(true); setError(""); try { const base = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:5080"; const response = await fetch(`${base}/api/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ identity: data.get("identity"), password: data.get("password") }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message ?? "Invalid username or password."); setSessionAccessToken(body.accessToken); const requestedPath = new URLSearchParams(window.location.search).get("next"); const destination = requestedPath?.startsWith("/") && !requestedPath.startsWith("//") ? requestedPath : "/"; router.push(destination); } catch (ex) { setError(ex instanceof Error ? ex.message : "Invalid username or password."); } finally { setBusy(false); } }
  return <form className="auth-form" onSubmit={submit} noValidate><h1>Sign in</h1><p className="auth-subtitle">Access the Customs Management System</p>{error && <p className="auth-error" role="alert">{error}</p>}<label>Username or Email<input name="identity" autoComplete="username" placeholder="Username or Email" /></label><label>Password<div className="password-wrap"><input name="password" type="password" autoComplete="current-password" placeholder="Password"/><span>◉</span></div></label><div className="auth-options"><label className="check"><input type="checkbox"/> Remember me</label><Link href="/forgot-password">Forgot password?</Link></div><button className="auth-primary" type="submit" disabled={busy}>{busy ? "Signing in…" : "Sign In　→"}</button><div className="or"><span>or</span></div><button className="iam-button" type="button">♢　Login with Government IAM</button><p className="auth-register">Don’t have an account? <Link href="/signup">Create an account</Link></p></form>;
}

export function SignupForm() {
  const [error, setError] = useState(""); const [sent, setSent] = useState(false);
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); const required = ["fullName", "staffId", "email", "department", "role", "password", "confirm"]; if (required.some(k => !data.get(k))) { setError("Complete all required fields."); return; } if (data.get("password") !== data.get("confirm")) { setError("Passwords do not match."); return; } if (!/(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z]).{8,}/.test(String(data.get("password")))) { setError("Password does not meet the requirements."); return; } try { const base = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:5080"; const response = await fetch(`${base}/api/auth/register`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fullName: data.get("fullName"), staffId: data.get("staffId"), email: data.get("email"), phone: data.get("phone"), department: data.get("department"), role: data.get("role"), password: data.get("password"), confirmPassword: data.get("confirm") }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message ?? "Unable to submit registration."); setError(""); setSent(true); } catch (ex) { setError(ex instanceof Error ? ex.message : "Unable to submit registration."); } }
  return <form className="auth-form signup-form" onSubmit={submit} noValidate><h1>Create Your Account</h1><p className="auth-subtitle">Register to access the Customs Management System</p><p className="auth-note">Account creation is subject to approval by the System Administrator.</p>{error && <p className="auth-error" role="alert">{error}</p>}{sent && <p className="auth-success" role="status">Request submitted for administrator approval.</p>}<div className="form-grid"><label>Full Name <em>*</em><input name="fullName" placeholder="Enter your full name"/></label><label>Employee/Staff ID <em>*</em><input name="staffId" placeholder="Enter your employee ID"/></label><label>Email Address <em>*</em><input name="email" type="email" placeholder="name@organization.et"/></label><label>Phone Number<input name="phone" placeholder="+251 9XX XXX XXX"/></label><label>Department / Office <em>*</em><select name="department" defaultValue=""><option value="" disabled>Select department</option><option>Head Office</option><option>Regional Office</option><option>Port Office</option></select></label><label>User Role <em>*</em><select name="role" defaultValue=""><option value="" disabled>Select role</option><option>Customs Officer</option><option>Customs Administrator</option></select></label><label className="wide">Password <em>*</em><input name="password" type="password" placeholder="Create a secure password"/></label><label className="wide">Confirm Password <em>*</em><input name="confirm" type="password" placeholder="Re-enter your password"/></label></div><div className="password-requirements"><b>Password Requirements:</b><span>✓ Minimum 8 characters　 ✓ At least one uppercase letter　 ✓ At least one number</span><span>✓ At least one lowercase letter　 ✓ At least one special character</span></div><label className="check terms"><input type="checkbox" required/> I have read and agree to the system’s <a href="#terms">Terms of Use</a> and <a href="#security">Security Policy</a>.</label><button className="auth-primary" type="submit">♙　Create Account</button></form>;
}
