"use client";
import { useEffect, useState } from "react";
type Request = { id: string; fullName: string; staffId: string; email: string; department: string; role: string; status: string; submittedAt: string };
type User = { id: string; username: string; fullName: string; email: string; role: string; active: boolean };
export default function AdministrationPage() {
  const [requests, setRequests] = useState<Request[]>([]); const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [approving, setApproving] = useState("");
  async function load() { const token = window.localStorage.getItem("customs_access_token"); if (!token) { setError("Sign in as a System Administrator to manage users."); setLoading(false); return; } const base = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:5080"; try { const headers = { Authorization: `Bearer ${token}` }; const [requestResponse, userResponse] = await Promise.all([fetch(`${base}/api/auth/registration-requests`, { headers }), fetch(`${base}/api/auth/users`, { headers })]); if (!requestResponse.ok || !userResponse.ok) throw new Error("You need System Administrator access to view user control."); const requestBody = await requestResponse.json(); const userBody = await userResponse.json(); setRequests(requestBody.requests); setUsers(userBody.users); } catch (ex) { setError(ex instanceof Error ? ex.message : "Unable to load users."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function approve(id: string) { const token = window.localStorage.getItem("customs_access_token"); const base = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:5080"; setApproving(id); try { const response = await fetch(`${base}/api/auth/registration-requests/${id}/approve`, { method: "POST", headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error("Approval failed."); await load(); } catch (ex) { setError(ex instanceof Error ? ex.message : "Approval failed."); } finally { setApproving(""); } }
  return <><p className="eyebrow">Administration</p><h1>User control</h1><p className="lead">Review registration requests and manage active system users.</p>{error && <p className="auth-error" role="alert">{error}</p>}{loading ? <p>Loading user control…</p> : <><section className="user-control-summary"><div><strong>{requests.length}</strong><span>Pending requests</span></div><div><strong>{users.length}</strong><span>Active users</span></div><div><strong>3</strong><span>System roles</span></div></section><section className="admin-panel"><div className="panel-heading"><div><h2>Pending registration requests</h2><p>Only a System Administrator can approve account access.</p></div><button type="button" onClick={() => void load()}>Refresh</button></div>{requests.length === 0 ? <p className="empty-state">No pending registration requests.</p> : <div className="table-wrap"><table><thead><tr><th>Applicant</th><th>Department</th><th>Requested role</th><th>Submitted</th><th>Status</th><th>Action</th></tr></thead><tbody>{requests.map(request => <tr key={request.id}><td><strong>{request.fullName}</strong><small>{request.email}<br/>{request.staffId}</small></td><td>{request.department}</td><td>{request.role}</td><td>{new Date(request.submittedAt).toLocaleDateString()}</td><td><span className="status-pending">Pending</span></td><td><button className="approve-button" type="button" disabled={approving === request.id} onClick={() => void approve(request.id)}>{approving === request.id ? "Approving…" : "Approve"}</button></td></tr>)}</tbody></table></div>}</section><section className="admin-panel"><div className="panel-heading"><div><h2>Active users</h2><p>Current accounts and assigned RBAC roles.</p></div></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td>{user.fullName}<small>@{user.username}</small></td><td>{user.email}</td><td>{user.role}</td><td><span className="status-active">{user.active ? "Active" : "Inactive"}</span></td></tr>)}</tbody></table></div></section></>}</>;
}
