"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { FiArrowRight, FiBarChart2, FiBookOpen, FiCheckSquare, FiFileText, FiGlobe, FiMapPin, FiShield } from "react-icons/fi";
import { roleLabel, workspaceApi, type WorkspaceDashboard } from "@/lib/workspace";

export default function DashboardPage() {
  const [dashboard, setDashboard] = useState<WorkspaceDashboard | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void workspaceApi<WorkspaceDashboard>("/dashboard").then(setDashboard).catch(exception => setError(exception instanceof Error ? exception.message : "Unable to load your workspace.")); }, []);
  if (error) return <section className="dashboard-empty"><h1>Workspace unavailable</h1><p>{error}</p></section>;
  if (!dashboard) return <section className="dashboard-empty"><p>Loading your customs valuation workspace…</p></section>;
  return <section className="workspace-dashboard"><div className="dashboard-heading"><div><p className="eyebrow">{roleLabel(dashboard.role)}</p><h1>Welcome to your workspace</h1><p className="lead">Your secure dashboard for customs valuation, evidence review and operational decisions.</p></div><span className="workspace-tag"><FiShield /> Authorized access</span></div><div className="dashboard-kpis">{dashboard.kpis.map(kpi => <article className={`dashboard-kpi dashboard-kpi--${kpi.tone}`} key={kpi.key}><span>{kpi.label}</span><strong>{kpi.value}</strong><small>{kpi.detail}</small></article>)}</div><div className="dashboard-main-grid"><section className="dashboard-panel"><div className="dashboard-panel-heading"><div><p className="eyebrow">Evidence workspace</p><h2>Start a valuation task</h2><span>Search classifications and reference-price evidence.</span></div></div><div className="dashboard-action-grid"><Link href="/hs-codes"><FiBookOpen /><span><b>HS code search</b><small>Find tariff and classification data</small></span><FiArrowRight /></Link><Link href="/valuation-decisions"><FiCheckSquare /><span><b>Valuation decisions</b><small>Review and record evidence-based decisions</small></span><FiArrowRight /></Link><Link href="/analytics"><FiBarChart2 /><span><b>Analytics</b><small>Explore price statistics and trends</small></span><FiArrowRight /></Link></div></section><section className="dashboard-panel"><div className="dashboard-panel-heading"><div><p className="eyebrow">Operational scope</p><h2>Your customs locations</h2><span>Authorized offices and current service status.</span></div></div><div className="dashboard-location-list">{dashboard.locations.slice(0, 5).map(location => <div key={location.id}><FiMapPin /><span><b>{location.displayName || location.name}</b><small>{location.officialCode} · {location.locationType}</small></span><em>{location.status}</em></div>)}</div></section><section className="dashboard-panel dashboard-panel--full"><div className="dashboard-panel-heading"><div><p className="eyebrow">Recent activity</p><h2>Valuation decisions</h2><span>Latest decisions visible within your role scope.</span></div><Link href="/valuation-decisions">Open decisions <FiArrowRight /></Link></div>{dashboard.decisions.length ? <div className="dashboard-decision-list">{dashboard.decisions.slice(0, 5).map(item => <div key={item.id}><FiFileText /><span><b>{item.product || item.hsCode}</b><small>{item.hsCode} · {item.recordedAt ? new Date(item.recordedAt).toLocaleDateString() : "Current"}</small></span><strong>{item.selectedReferenceValue.toLocaleString()} {item.currency}</strong><em>{item.status}</em></div>)}</div> : <p className="dashboard-no-data">No valuation decisions are available in your current scope.</p>}</section></div></section>;
}
