// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SES.Customs.Infrastructure.Context;

#nullable disable

namespace SES.Customs.Infrastructure.Context.Migrations
{
    [DbContext(typeof(CustomsDbContext))]
    [Migration("20260915093915_AddLocalMarketObservations")]
    partial class AddLocalMarketObservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SES.Customs.Core.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Decision")
                        .HasColumnType("text");

                    b.Property<string>("IpDeviceInformation")
                        .HasColumnType("text");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousValueJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecordId", "OccurredAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.DecisionEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComparisonRuleVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("HistoricalCustomsPriceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InternationalPriceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocalPriceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("HistoricalCustomsPriceId");

                    b.HasIndex("InternationalPriceId");

                    b.HasIndex("LocalPriceId");

                    b.ToTable("decision_evidence", null, t =>
                        {
                            t.HasCheckConstraint("ck_one_evidence_pool", "num_nonnulls(\"InternationalPriceId\", \"LocalPriceId\", \"HistoricalCustomsPriceId\") = 1");
                        });
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConvertedCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NbeSourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rate")
                        .HasPrecision(24, 12)
                        .HasColumnType("numeric(24,12)");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OriginalCurrency", "ConvertedCurrency", "RateDate");

                    b.ToTable("exchange_rates", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HsCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("DescriptionAm")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId", "Code")
                        .IsUnique();

                    b.ToTable("hs_codes", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HsCodeCorrelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MappingGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ToCodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromCodeId");

                    b.HasIndex("MappingGroupId");

                    b.HasIndex("ToCodeId");

                    b.ToTable("hs_code_correlations", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HsRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("hs_revisions", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.LocalMarket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NameAm")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("local_markets", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.LocalMarketObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("ClassificationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DuplicateOfId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExcludedKeywordsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("HsCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPotentialOutlier")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ListingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ListingDescription")
                        .HasColumnType("text");

                    b.Property<string>("ListingTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListingUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("ManualReviewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchedKeywordsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("NormalizedPrice")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("NormalizedQuantity")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("NormalizedUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("NormalizedUnitPrice")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("OriginalQuantity")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("OriginalUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutlierMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutlierReason")
                        .HasColumnType("text");

                    b.Property<decimal?>("OutlierScore")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductType")
                        .HasColumnType("text");

                    b.Property<string>("RawCategory")
                        .HasColumnType("text");

                    b.Property<string>("RawCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("RawPrice")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<int>("RelevanceScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RetrievalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewJustification")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SellerName")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceListingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetProfileJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Variant")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DuplicateOfId");

                    b.HasIndex("SourceId", "SourceListingId")
                        .IsUnique();

                    b.HasIndex("HsCodeId", "ClassificationStatus", "RetrievalDate");

                    b.ToTable("local_market_observations", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.NationalTariffLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAm")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duty")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HsCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("HsCodeId", "Code", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("national_tariff_lines", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.PriceEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrandModel")
                        .HasColumnType("text");

                    b.Property<string>("ConvertedCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("ConvertedValue")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExchangeRateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HsCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("OriginalValue")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QualityGrade")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeRateId");

                    b.HasIndex("SourceId");

                    b.HasIndex("HsCodeId", "PriceDate");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.PriceSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pool")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("price_sources", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ValuationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HsCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficerSubjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SelectedReferenceValue")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.HasKey("Id");

                    b.HasIndex("HsCodeId");

                    b.ToTable("valuation_decisions", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Infrastructure.Context.AuthAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AuthAccounts");
                });

            modelBuilder.Entity("SES.Customs.Infrastructure.Context.RegistrationRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status", "SubmittedAt");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HistoricalCustomsPrice", b =>
                {
                    b.HasBaseType("SES.Customs.Core.Models.PriceEvidence");

                    b.Property<string>("AuthorizationReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeclarationReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Incoterm")
                        .HasColumnType("text");

                    b.Property<string>("SourceCountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValuationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("historical_customs_prices", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.InternationalReferencePrice", b =>
                {
                    b.HasBaseType("SES.Customs.Core.Models.PriceEvidence");

                    b.Property<decimal?>("Freight")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("ImportCountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Incoterm")
                        .HasColumnType("text");

                    b.Property<decimal?>("Insurance")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("SourceCountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradeFlow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradePeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("reference_prices", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.LocalMarketPrice", b =>
                {
                    b.HasBaseType("SES.Customs.Core.Models.PriceEvidence");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("OtherTaxesIncluded")
                        .HasColumnType("boolean");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("TransportIncluded")
                        .HasColumnType("boolean");

                    b.Property<bool?>("VatIncluded")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("VerificationDate")
                        .HasColumnType("date");

                    b.HasIndex("MarketId");

                    b.ToTable("local_prices", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.DecisionEvidence", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.ValuationDecision", null)
                        .WithMany("Evidence")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SES.Customs.Core.Models.HistoricalCustomsPrice", null)
                        .WithMany()
                        .HasForeignKey("HistoricalCustomsPriceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SES.Customs.Core.Models.InternationalReferencePrice", null)
                        .WithMany()
                        .HasForeignKey("InternationalPriceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SES.Customs.Core.Models.LocalMarketPrice", null)
                        .WithMany()
                        .HasForeignKey("LocalPriceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HsCode", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.HsRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HsCodeCorrelation", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("FromCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("ToCodeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.LocalMarketObservation", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.LocalMarketObservation", null)
                        .WithMany()
                        .HasForeignKey("DuplicateOfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("HsCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SES.Customs.Core.Models.PriceSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.NationalTariffLine", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("HsCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.PriceEvidence", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.ExchangeRate", null)
                        .WithMany()
                        .HasForeignKey("ExchangeRateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("HsCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SES.Customs.Core.Models.PriceSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ValuationDecision", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("HsCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.LocalMarketPrice", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.LocalMarket", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ValuationDecision", b =>
                {
                    b.Navigation("Evidence");
                });
#pragma warning restore 612, 618
        }
    }
}
