// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SES.Customs.Infrastructure.Context;

#nullable disable

namespace SES.Customs.Infrastructure.Context.Migrations
{
    [DbContext(typeof(CustomsDbContext))]
    partial class CustomsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SES.Customs.Core.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewReason")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Decision")
                        .HasColumnType("text");

                    b.Property<string>("IpDeviceInformation")
                        .HasColumnType("text");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousValueJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "OccurredAt");

                    b.HasIndex("RecordId", "OccurredAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.DecisionEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComparisonRuleVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("HistoricalCustomsPriceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InternationalPriceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocalPriceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("HistoricalCustomsPriceId");

                    b.HasIndex("InternationalPriceId");

                    b.HasIndex("LocalPriceId");

                    b.ToTable("decision_evidence", null, t =>
                        {
                            t.HasCheckConstraint("ck_one_evidence_pool", "num_nonnulls(\"InternationalPriceId\", \"LocalPriceId\", \"HistoricalCustomsPriceId\") = 1");
                        });
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConvertedCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NbeSourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rate")
                        .HasPrecision(24, 12)
                        .HasColumnType("numeric(24,12)");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OriginalCurrency", "ConvertedCurrency", "RateDate");

                    b.ToTable("exchange_rates", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HsCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("DescriptionAm")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HsUpdateCandidatesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("HsUpdateNote")
                        .HasColumnType("text");

                    b.Property<string>("HsUpdateStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SectionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId", "Code")
                        .IsUnique();

                    b.ToTable("hs_codes", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HsCodeCorrelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MappingGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ToCodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromCodeId");

                    b.HasIndex("MappingGroupId");

                    b.HasIndex("ToCodeId");

                    b.ToTable("hs_code_correlations", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HsCodeUpdateMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceHsCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetDescription")
                        .HasColumnType("text");

                    b.Property<string>("TargetHsCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId", "SourceHsCode");

                    b.HasIndex("RevisionId", "TargetHsCode");

                    b.ToTable("hs_code_update_mappings", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HsRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalHsVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedHsVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("hs_revisions", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.LocalMarket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NameAm")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("local_markets", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.LocalMarketObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("ClassificationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DuplicateOfId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExcludedKeywordsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("HsCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPotentialOutlier")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ListingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ListingDescription")
                        .HasColumnType("text");

                    b.Property<string>("ListingTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListingUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("ManualReviewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchedKeywordsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("NormalizedPrice")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("NormalizedQuantity")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("NormalizedUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("NormalizedUnitPrice")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("OriginalQuantity")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("OriginalUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutlierMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutlierReason")
                        .HasColumnType("text");

                    b.Property<decimal?>("OutlierScore")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductType")
                        .HasColumnType("text");

                    b.Property<string>("RawCategory")
                        .HasColumnType("text");

                    b.Property<string>("RawCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("RawPrice")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<int>("RelevanceScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RetrievalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewJustification")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SellerName")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceListingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetProfileJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Variant")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DuplicateOfId");

                    b.HasIndex("SourceId", "SourceListingId")
                        .IsUnique();

                    b.HasIndex("HsCodeId", "ClassificationStatus", "RetrievalDate");

                    b.ToTable("local_market_observations", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.MarketPriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ObservedDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ObservedDate");

                    b.ToTable("market_price_snapshots", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.NationalTariffLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAm")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duty")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HsCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TariffItemNo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("HsCodeId", "Code", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("national_tariff_lines", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.PriceEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrandModel")
                        .HasColumnType("text");

                    b.Property<string>("ConvertedCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("ConvertedValue")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExchangeRateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HsCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("OriginalValue")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QualityGrade")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeRateId");

                    b.HasIndex("SourceId");

                    b.HasIndex("HsCodeId", "PriceDate");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.PriceSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pool")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("price_sources", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ValuationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("HsCodeId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("InitialDuty")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("InitialDutyCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocationSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OfficerSubjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewJustification")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("SelectedReferenceValue")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HsCodeId");

                    b.HasIndex("LocationId", "Status");

                    b.ToTable("valuation_decisions", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ValuationPhase2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdjustmentReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CalculationRuleVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("CustomsValueAmount")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("CustomsValueCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(24, 12)
                        .HasColumnType("numeric(24,12)");

                    b.Property<DateOnly?>("ExchangeRateDate")
                        .HasColumnType("date");

                    b.Property<string>("ExchangeRateSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ExciseTaxApplicable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ExemptionAmount")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("ExemptionCodes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("InitialDutyAmount")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("InitialDutyCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsCommercialImport")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ManualAdjustmentAmount")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("ManualAdjustmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OfficerConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("OriginPreferenceClaimed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OriginalHsCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("SelectedHsCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TargetCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("TotalAdditionalTax")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("TotalTax")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<Guid>("ValuationDecisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WaiverAmount")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<bool>("WithholdingApplicable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OriginalHsCodeId");

                    b.HasIndex("SelectedHsCodeId");

                    b.HasIndex("ValuationDecisionId")
                        .IsUnique();

                    b.ToTable("valuation_phase2", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ValuationPhase2TaxLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("CalculatedAmount")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("CalculationBasis")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsApplicable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal>("RecommendedValue")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ValuationPhase2Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.HasKey("Id");

                    b.HasIndex("ValuationPhase2Id", "Order");

                    b.ToTable("valuation_phase2_tax_lines", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Infrastructure.Context.AuthAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PrimaryLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PrimaryLocationId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AuthAccounts");
                });

            modelBuilder.Entity("SES.Customs.Infrastructure.Context.CustomsLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BorderCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CityWoreda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEntryPoint")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExitPoint")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficialCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SupportsExport")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsImport")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsInspection")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsTransit")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsValuation")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OfficialCode")
                        .IsUnique();

                    b.HasIndex("ParentLocationId");

                    b.ToTable("customs_locations", (string)null, t =>
                        {
                            t.HasCheckConstraint("CK_customs_locations_coordinates_complete", "(\"Latitude\" IS NULL AND \"Longitude\" IS NULL) OR (\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL)");
                            t.HasCheckConstraint("CK_customs_locations_coordinates_ethiopia", "\"Latitude\" IS NULL OR (\"Latitude\" >= 3.35 AND \"Latitude\" <= 14.95 AND \"Longitude\" >= 33.00 AND \"Longitude\" <= 48.05)");
                            t.HasCheckConstraint("CK_customs_locations_location_type", "\"LocationType\" IN ('REGION', 'BRANCH')");
                        });
                });

            modelBuilder.Entity("SES.Customs.Infrastructure.Context.CustomsLocationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomsLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValueJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousValueJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomsLocationId", "ChangedAt");

                    b.ToTable("customs_location_history", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Infrastructure.Context.RegistrationRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.HasIndex("Status", "SubmittedAt");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HistoricalCustomsPrice", b =>
                {
                    b.HasBaseType("SES.Customs.Core.Models.PriceEvidence");

                    b.Property<string>("AuthorizationReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeclarationReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Incoterm")
                        .HasColumnType("text");

                    b.Property<string>("SourceCountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValuationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("historical_customs_prices", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.InternationalReferencePrice", b =>
                {
                    b.HasBaseType("SES.Customs.Core.Models.PriceEvidence");

                    b.Property<decimal?>("Freight")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("ImportCountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Incoterm")
                        .HasColumnType("text");

                    b.Property<decimal?>("Insurance")
                        .HasPrecision(24, 8)
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("SourceCountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradeFlow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradePeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("reference_prices", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.LocalMarketPrice", b =>
                {
                    b.HasBaseType("SES.Customs.Core.Models.PriceEvidence");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("OtherTaxesIncluded")
                        .HasColumnType("boolean");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("TransportIncluded")
                        .HasColumnType("boolean");

                    b.Property<bool?>("VatIncluded")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("VerificationDate")
                        .HasColumnType("date");

                    b.HasIndex("MarketId");

                    b.ToTable("local_prices", (string)null);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.DecisionEvidence", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.ValuationDecision", null)
                        .WithMany("Evidence")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SES.Customs.Core.Models.HistoricalCustomsPrice", null)
                        .WithMany()
                        .HasForeignKey("HistoricalCustomsPriceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SES.Customs.Core.Models.InternationalReferencePrice", null)
                        .WithMany()
                        .HasForeignKey("InternationalPriceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SES.Customs.Core.Models.LocalMarketPrice", null)
                        .WithMany()
                        .HasForeignKey("LocalPriceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HsCode", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.HsRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.HsCodeCorrelation", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("FromCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("ToCodeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.LocalMarketObservation", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.LocalMarketObservation", null)
                        .WithMany()
                        .HasForeignKey("DuplicateOfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("HsCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SES.Customs.Core.Models.PriceSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.NationalTariffLine", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("HsCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.PriceEvidence", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.ExchangeRate", null)
                        .WithMany()
                        .HasForeignKey("ExchangeRateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("HsCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SES.Customs.Core.Models.PriceSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ValuationDecision", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("HsCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SES.Customs.Infrastructure.Context.CustomsLocation", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ValuationPhase2", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("OriginalHsCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SES.Customs.Core.Models.HsCode", null)
                        .WithMany()
                        .HasForeignKey("SelectedHsCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SES.Customs.Core.Models.ValuationDecision", null)
                        .WithOne()
                        .HasForeignKey("SES.Customs.Core.Models.ValuationPhase2", "ValuationDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ValuationPhase2TaxLine", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.ValuationPhase2", null)
                        .WithMany("TaxLines")
                        .HasForeignKey("ValuationPhase2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Infrastructure.Context.AuthAccountEntity", b =>
                {
                    b.HasOne("SES.Customs.Infrastructure.Context.CustomsLocation", null)
                        .WithMany()
                        .HasForeignKey("PrimaryLocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SES.Customs.Infrastructure.Context.CustomsLocation", b =>
                {
                    b.HasOne("SES.Customs.Infrastructure.Context.CustomsLocation", null)
                        .WithMany()
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SES.Customs.Infrastructure.Context.CustomsLocationHistory", b =>
                {
                    b.HasOne("SES.Customs.Infrastructure.Context.CustomsLocation", null)
                        .WithMany()
                        .HasForeignKey("CustomsLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Infrastructure.Context.UserLocationScope", b =>
                {
                    b.HasOne("SES.Customs.Infrastructure.Context.CustomsLocation", null)
                        .WithMany()
                        .HasForeignKey("CustomsLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SES.Customs.Infrastructure.Context.AuthAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.LocalMarketPrice", b =>
                {
                    b.HasOne("SES.Customs.Core.Models.LocalMarket", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ValuationDecision", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("SES.Customs.Core.Models.ValuationPhase2", b =>
                {
                    b.Navigation("TaxLines");
                });
#pragma warning restore 612, 618
        }
    }
}
