"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import {
  FiActivity, FiAlertTriangle, FiBarChart2, FiCheckCircle, FiClock, FiFilter, FiMapPin,
  FiRefreshCw, FiShield, FiTrendingUp, FiUsers,
} from "react-icons/fi";
import { DataState } from "@/components/DataState";
import { PlannedModule } from "@/components/PlannedModule";
import { roleLabel, workspaceApi, type CustomsAdminAnalytics, type WorkspaceProfile } from "@/lib/workspace";

function inputDate(value: Date) { return value.toISOString().slice(0, 10); }
function formatNumber(value: number) { return value.toLocaleString(); }
function formatHours(value: number | null) { return value == null ? "—" : `${value.toLocaleString(undefined, { maximumFractionDigits: 1 })} h`; }
function formatDate(value: string | null) { return value ? new Date(value).toLocaleDateString() : "No activity"; }
function formatDateTime(value: string) { return new Date(value).toLocaleString(); }

function MetricCard({ label, value, detail, tone = "blue", icon }: { label: string; value: string; detail: string; tone?: string; icon: React.ReactNode }) {
  return <article className={`analytics-metric analytics-metric--${tone}`}><span className="analytics-metric-icon">{icon}</span><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>;
}

function StatusBars({ rows, total }: { rows: CustomsAdminAnalytics["statusBreakdown"]; total: number }) {
  if (!rows.length) return <DataState kind="empty" compact title="No valuation cases" description="Valuation status data will appear as Officers record and submit cases." />;
  return <div className="analytics-status-bars">{rows.map(row => <div className="analytics-status-row" key={row.status}><div><strong>{row.status}</strong><span>{row.percentage.toLocaleString()}%</span></div><div className="analytics-progress"><i className={`analytics-progress-fill analytics-progress-fill--${row.status.toLowerCase()}`} style={{ width: `${total ? Math.max(row.percentage, 2) : 0}%` }} /></div><small>{formatNumber(row.count)} case{row.count === 1 ? "" : "s"}</small></div>)}</div>;
}

function TrendBars({ rows, outlier = false }: { rows: CustomsAdminAnalytics["trends"] | CustomsAdminAnalytics["quality"]["outlierTrend"]; outlier?: boolean }) {
  const valueFor = (row: CustomsAdminAnalytics["trends"][number] | CustomsAdminAnalytics["quality"]["outlierTrend"][number]) => outlier && "count" in row ? row.count : !outlier && "decisions" in row ? row.decisions : 0;
  const max = Math.max(1, ...rows.map(valueFor));
  if (!rows.length) return <DataState kind="empty" compact title="No trend data" description="More records are needed to draw a trend." />;
  return <div className="analytics-trend-chart" role="img" aria-label={outlier ? "Reference outlier trend" : "Valuation decision trend"}>{rows.map(row => { const value = valueFor(row); return <div className="analytics-trend-column" key={row.period} title={`${row.label}: ${value}`}><i style={{ height: `${Math.max(value ? (value / max) * 100 : 3, 3)}%` }} /><span>{row.label}</span></div>; })}</div>;
}

export default function AnalyticsPage() {
  const initialTo = inputDate(new Date());
  const initialFrom = inputDate(new Date(Date.now() - 30 * 24 * 60 * 60 * 1000));
  const [profile, setProfile] = useState<WorkspaceProfile | null>(null);
  const [analytics, setAnalytics] = useState<CustomsAdminAnalytics | null>(null);
  const [filters, setFilters] = useState({ from: initialFrom, to: initialTo, locationId: "", officerId: "", status: "", hsChapter: "", currency: "" });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const current = await workspaceApi<WorkspaceProfile>("/me");
      setProfile(current);
      if (current.user.role !== "CustomsAdministrator") return;
      const params = new URLSearchParams({ dateFrom: `${filters.from}T00:00:00.000Z`, dateTo: `${filters.to}T23:59:59.999Z` });
      if (filters.locationId) params.set("locationId", filters.locationId);
      if (filters.officerId) params.set("officerId", filters.officerId);
      if (filters.status) params.set("status", filters.status);
      if (filters.hsChapter) params.set("hsChapter", filters.hsChapter);
      if (filters.currency) params.set("currency", filters.currency);
      setAnalytics(await workspaceApi<CustomsAdminAnalytics>(`/analytics?${params.toString()}`));
    } catch (ex) { setError(ex instanceof Error ? ex.message : "Analytics could not be loaded."); }
    finally { setLoading(false); }
  }, [filters]);

  useEffect(() => { void load(); }, [load]);

  function submitFilters(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void load(); }

  if (loading && !analytics) return <DataState kind="loading" title="Loading operational analytics" description="Calculating regional valuation, workforce, quality, and audit measures." />;
  if (!profile) return <DataState kind="error" title="Analytics are unavailable" description={error} onRetry={() => void load()} />;
  if (profile.user.role !== "CustomsAdministrator") return <PlannedModule titleKey="analytics" />;
  if (!analytics) return <DataState kind="error" title="Analytics are unavailable" description={error} onRetry={() => void load()} />;

  const { summary, quality } = analytics;
  const maxBranchDecisions = Math.max(1, ...analytics.branchPerformance.map(branch => branch.decisions));
  const maxOfficerDecisions = Math.max(1, ...analytics.officerPerformance.map(officer => officer.decisions));
  const topActivity = analytics.auditActivity.slice(0, 8);
  const currencies = Array.from(new Set(analytics.topHsCodes.flatMap(row => row.currencies.split(", ").filter(Boolean))));

  return <div className="management-page analytics-page">
    <div className="page-heading"><div><p className="eyebrow">Monitoring</p><h1>Regional operational analytics</h1><p className="lead">Track valuation workload, employee capacity, decision quality, shared reference signals, and audited activity for your assigned region.</p></div><div className="analytics-heading-actions"><span className="workspace-tag"><FiShield />{roleLabel(profile.user.role)}</span><button className="secondary-button" type="button" onClick={() => void load()} disabled={loading}><FiRefreshCw />{loading ? "Refreshing..." : "Refresh"}</button></div></div>
    <div className="role-banner"><span className="badge">{analytics.scope.region}</span><strong>{analytics.scope.branchCount} branch{analytics.scope.branchCount === 1 ? "" : "es"}</strong><span>{analytics.scope.activeBranches} active in the selected regional scope.</span></div>
    <p className="analytics-scope-note"><FiShield />{analytics.scopeNote}</p>
    {error && <DataState kind="error" compact title="The latest refresh failed" description={error} onRetry={() => void load()} />}

    <section className="admin-panel analytics-filter-panel"><div className="panel-heading"><div><p className="eyebrow">Filters</p><h2>Explore the operational period</h2><p>Filter valuation, workforce, and audit measures by branch, Officer, status, HS chapter, or currency.</p></div><FiFilter aria-hidden="true" /></div><form className="analytics-filter-grid" onSubmit={submitFilters}><label>From<input type="date" value={filters.from} max={filters.to} onChange={event => setFilters(current => ({ ...current, from: event.target.value }))} /></label><label>To<input type="date" value={filters.to} min={filters.from} onChange={event => setFilters(current => ({ ...current, to: event.target.value }))} /></label><label>Branch<select value={filters.locationId} onChange={event => setFilters(current => ({ ...current, locationId: event.target.value }))}><option value="">All assigned branches</option>{profile.locations.filter(location => location.locationType === "BRANCH").map(location => <option key={location.id} value={location.id}>{location.displayName || location.name} · {location.officialCode}</option>)}</select></label><label>Officer<select value={filters.officerId} onChange={event => setFilters(current => ({ ...current, officerId: event.target.value }))}><option value="">All Customs Officers</option>{analytics.officerPerformance.map(officer => <option key={officer.userId} value={officer.userId}>{officer.name}{officer.employeeNumber ? ` · ${officer.employeeNumber}` : ""}</option>)}</select></label><label>Status<select value={filters.status} onChange={event => setFilters(current => ({ ...current, status: event.target.value }))}><option value="">All statuses</option><option value="Draft">Draft</option><option value="Submitted">Submitted</option><option value="Returned">Returned</option><option value="Approved">Approved</option><option value="Rejected">Rejected</option></select></label><label>HS chapter<input inputMode="numeric" maxLength={4} value={filters.hsChapter} onChange={event => setFilters(current => ({ ...current, hsChapter: event.target.value.replace(/\D/g, "").slice(0, 4) }))} placeholder="e.g. 85 or 8517" /></label><label>Currency<select value={filters.currency} onChange={event => setFilters(current => ({ ...current, currency: event.target.value }))}><option value="">All currencies</option>{currencies.map(value => <option key={value} value={value}>{value}</option>)}</select></label><div className="form-actions"><button className="primary-button" type="submit" disabled={loading}><FiBarChart2 />{loading ? "Calculating..." : "Apply filters"}</button></div></form></section>

    <section className="analytics-metric-grid" aria-label="Regional analytics summary"><MetricCard label="Active offices" value={formatNumber(summary.activeOffices)} detail={`${formatNumber(summary.totalOffices)} assigned branches`} tone="blue" icon={<FiMapPin />} /><MetricCard label="Active Officers" value={formatNumber(summary.activeOfficers)} detail={`${formatNumber(summary.managedOfficers)} managed accounts`} tone="teal" icon={<FiUsers />} /><MetricCard label="Pending valuations" value={formatNumber(summary.pendingValuations)} detail="Awaiting review" tone={summary.pendingValuations ? "gold" : "green"} icon={<FiClock />} /><MetricCard label="Returned valuations" value={formatNumber(summary.returnedValuations)} detail="Sent back for correction" tone={summary.returnedValuations ? "gold" : "green"} icon={<FiRefreshCw />} /><MetricCard label="Decisions today" value={formatNumber(summary.decisionsToday)} detail={`${formatNumber(summary.decisions)} in selected period`} tone="blue" icon={<FiCheckCircle />} /><MetricCard label="Suspended accounts" value={formatNumber(summary.suspendedAccounts)} detail="Suspended or locked Officers" tone={summary.suspendedAccounts ? "red" : "green"} icon={<FiShield />} /><MetricCard label="Review turnaround" value={formatHours(summary.averageReviewHours)} detail={`${formatNumber(summary.overdueReviews)} older than 48 hours`} tone={summary.overdueReviews ? "red" : "teal"} icon={<FiClock />} /><MetricCard label="Approval rate" value={`${summary.approvalRate.toLocaleString()}%`} detail={`Return ${summary.returnRate.toLocaleString()}% · Reject ${summary.rejectionRate.toLocaleString()}%`} tone="teal" icon={<FiTrendingUp />} /></section>

    <div className="analytics-content-grid"><section className="admin-panel analytics-panel analytics-panel--wide"><div className="panel-heading"><div><p className="eyebrow">Valuation workload</p><h2>Decision pipeline</h2><p>Cases recorded in the selected period, with the review queue highlighted.</p></div><Link className="secondary-button" href="/valuation-decisions">Open review queue</Link></div><StatusBars rows={analytics.statusBreakdown} total={summary.decisions} /></section><section className="admin-panel analytics-panel"><div className="panel-heading"><div><p className="eyebrow">Review performance</p><h2>Control measures</h2></div><FiActivity aria-hidden="true" /></div><dl className="analytics-stat-list"><div><dt>Approved</dt><dd>{formatNumber(summary.approvedValuations)} <small>({summary.approvalRate.toLocaleString()}%)</small></dd></div><div><dt>Returned</dt><dd>{formatNumber(summary.returnedValuations)} <small>({summary.returnRate.toLocaleString()}%)</small></dd></div><div><dt>Rejected</dt><dd>{formatNumber(summary.rejectedValuations)} <small>({summary.rejectionRate.toLocaleString()}%)</small></dd></div><div><dt>Justification coverage</dt><dd>{summary.justificationCoverage.toLocaleString()}%</dd></div><div><dt>Overdue reviews</dt><dd className={summary.overdueReviews ? "is-alert" : ""}>{formatNumber(summary.overdueReviews)}</dd></div></dl></section></div>

    <div className="analytics-content-grid"><section className="admin-panel analytics-panel analytics-panel--wide"><div className="panel-heading"><div><p className="eyebrow">Decision trend</p><h2>Valuation activity over time</h2><p>{analytics.trends.length ? `Showing ${analytics.trends[0].label} to ${analytics.trends[analytics.trends.length - 1].label}.` : "No activity in the selected period."}</p></div><FiBarChart2 aria-hidden="true" /></div><TrendBars rows={analytics.trends} /></section><section className="admin-panel analytics-panel"><div className="panel-heading"><div><p className="eyebrow">Alerts</p><h2>Requires attention</h2></div><FiAlertTriangle aria-hidden="true" /></div><div className="analytics-alert-list">{analytics.alerts.map((alert, index) => <article key={`${alert.title}-${index}`}><span className={`analytics-severity analytics-severity--${alert.severity.toLowerCase()}`}>{alert.severity}</span><div><strong>{alert.title}</strong><p>{alert.detail}</p></div></article>)}</div></section></div>

    <section className="admin-panel analytics-panel"><div className="panel-heading"><div><p className="eyebrow">Branch comparison</p><h2>Workload and review performance by branch</h2><p>Use the branch view to spot queue concentration, staffing gaps, and uneven turnaround.</p></div><Link className="secondary-button" href="/administration">Manage employees</Link></div>{analytics.branchPerformance.length ? <div className="table-wrap"><table className="analytics-table"><thead><tr><th>Branch</th><th>Officers</th><th>Decisions</th><th>Queue</th><th>Approved</th><th>Returned</th><th>Review time</th><th>Last decision</th></tr></thead><tbody>{analytics.branchPerformance.map(branch => <tr key={branch.locationId}><td><strong>{branch.name}</strong><small>{branch.officialCode} · {branch.active ? "Active" : branch.status}</small></td><td>{formatNumber(branch.officers)}</td><td><div className="analytics-inline-bar"><i style={{ width: `${Math.max(branch.decisions ? branch.decisions / maxBranchDecisions * 100 : 0, branch.decisions ? 4 : 0)}%` }} /><span>{formatNumber(branch.decisions)}</span></div></td><td><span className={branch.pending ? "analytics-number-alert" : ""}>{formatNumber(branch.pending)}</span></td><td>{formatNumber(branch.approved)}</td><td>{formatNumber(branch.returned)}</td><td>{formatHours(branch.averageReviewHours)}</td><td>{formatDate(branch.lastDecisionAt)}</td></tr>)}</tbody></table></div> : <DataState kind="empty" compact title="No assigned branches" description="Branch analytics will appear after a region and branch assignment is configured." />}</section>

    <section className="admin-panel analytics-panel"><div className="panel-heading"><div><p className="eyebrow">Workforce capacity</p><h2>Officer workload and access</h2><p>Review responsibilities, activity, case load, and access status together.</p></div><Link className="secondary-button" href="/administration">Open employee register</Link></div>{analytics.officerPerformance.length ? <div className="table-wrap"><table className="analytics-table"><thead><tr><th>Officer</th><th>Branch</th><th>Responsibilities</th><th>Cases</th><th>Queue</th><th>Review time</th><th>Last sign-in</th><th>Status</th></tr></thead><tbody>{analytics.officerPerformance.map(officer => <tr key={officer.userId}><td><strong>{officer.name}</strong><small>{officer.employeeNumber || "No staff ID"}</small></td><td>{officer.branch}</td><td>{officer.responsibilities || "Not recorded"}</td><td><div className="analytics-inline-bar"><i style={{ width: `${Math.max(officer.decisions ? officer.decisions / maxOfficerDecisions * 100 : 0, officer.decisions ? 4 : 0)}%` }} /><span>{formatNumber(officer.decisions)}</span></div></td><td>{formatNumber(officer.pending)}</td><td>{formatHours(officer.averageReviewHours)}</td><td>{formatDate(officer.lastLoginAt)}</td><td><span className={officer.active && officer.status === "ACTIVE" ? "status-active" : "status-pending"}>{officer.status}</span></td></tr>)}</tbody></table></div> : <DataState kind="empty" compact title="No Customs Officers" description="Create or assign Officers to see workforce analytics." />}</section>

    <div className="analytics-content-grid"><section className="admin-panel analytics-panel analytics-panel--wide"><div className="panel-heading"><div><p className="eyebrow">Quality and risk</p><h2>Reference and decision quality</h2><p>{quality.sharedReferenceData ? "Shared reference observations are shown separately from branch-scoped decisions." : "Quality measures are scoped to your region."}</p></div><FiTrendingUp aria-hidden="true" /></div><div className="analytics-quality-grid"><div><span>Missing evidence</span><strong>{formatNumber(quality.missingEvidence)}</strong><small>{summary.evidenceCoverage.toLocaleString()}% coverage</small></div><div><span>Missing justification</span><strong>{formatNumber(quality.missingJustification)}</strong><small>{summary.justificationCoverage.toLocaleString()}% coverage</small></div><div><span>Potential outliers</span><strong>{formatNumber(quality.potentialOutliers)}</strong><small>{formatNumber(quality.unreviewedOutliers)} unreviewed</small></div><div><span>Local vs international</span><strong>{quality.localVsInternationalVariancePercent == null ? "—" : `${quality.localVsInternationalVariancePercent > 0 ? "+" : ""}${quality.localVsInternationalVariancePercent.toLocaleString()}%`}</strong><small>ETB medians where available</small></div></div><TrendBars rows={quality.outlierTrend} outlier /></section><section className="admin-panel analytics-panel"><div className="panel-heading"><div><p className="eyebrow">Reference sources</p><h2>Source coverage</h2></div><FiShield aria-hidden="true" /></div>{analytics.sourceCoverage.length ? <div className="analytics-source-list">{analytics.sourceCoverage.map(source => <div key={source.sourceId}><span><strong>{source.name}</strong><small>{source.pool}</small></span><b>{formatNumber(source.records)}</b><em className={source.approved ? "is-approved" : "is-review"}>{source.approved ? "Approved" : "Review"}</em></div>)}</div> : <DataState kind="empty" compact title="No source records" description="Reference source usage will appear after evidence is loaded." />}</section></div>

    <div className="analytics-content-grid"><section className="admin-panel analytics-panel analytics-panel--wide"><div className="panel-heading"><div><p className="eyebrow">HS and valuation patterns</p><h2>Most active HS items</h2><p>Top items by visible decision volume in the selected period.</p></div><Link className="secondary-button" href="/hs-codes">Search HS codes</Link></div>{analytics.topHsCodes.length ? <div className="table-wrap"><table className="analytics-table"><thead><tr><th>HS code</th><th>Decisions</th><th>Approved</th><th>Returned</th><th>Currency</th><th>Average reference</th></tr></thead><tbody>{analytics.topHsCodes.map(row => <tr key={row.hsCode}><td><strong>{row.hsCode}</strong><small>{row.description}</small></td><td>{formatNumber(row.decisions)}</td><td>{formatNumber(row.approved)}</td><td>{formatNumber(row.returned)}</td><td>{row.currencies || "—"}</td><td>{row.averageReferenceValue == null ? "Mixed / unavailable" : row.averageReferenceValue.toLocaleString()}</td></tr>)}</tbody></table></div> : <DataState kind="empty" compact title="No HS activity" description="HS patterns will appear after valuation decisions are recorded." />}</section><section className="admin-panel analytics-panel"><div className="panel-heading"><div><p className="eyebrow">Audit summary</p><h2>Recorded activity</h2></div><Link className="secondary-button" href="/audit">Open audit activity</Link></div>{analytics.auditSummary.length ? <div className="analytics-audit-summary">{analytics.auditSummary.map(row => <div key={row.action}><span>{row.action.replaceAll("_", " ")}</span><b>{formatNumber(row.count)}</b></div>)}</div> : <DataState kind="empty" compact title="No audited activity" description="Audit events will appear as operations are performed." />}</section></div>

    <section className="admin-panel analytics-panel"><div className="panel-heading"><div><p className="eyebrow">Audit and compliance</p><h2>Recent regional activity</h2><p>Employee access, valuation review, and other auditable actions within the selected period.</p></div><FiActivity aria-hidden="true" /></div>{topActivity.length ? <div className="analytics-activity-list">{topActivity.map(activity => <article key={activity.id}><span className="activity-icon"><FiActivity /></span><div><strong>{activity.action.replaceAll("_", " ")}</strong><p>{activity.justification || `${activity.module} record updated`}</p><small>{activity.actor} · {activity.location} · {formatDateTime(activity.occurredAt)}</small></div></article>)}</div> : <DataState kind="empty" compact title="No activity in this period" description="Audited actions will appear here as the region is used." />}</section>
  </div>;
}
